### PR TITLE
Network selector updates

### LINKED ISSUE #242: Add functionality to NetworkSelector UI
Bildschirmfoto 2021-09-15 um 23 47 28

added some ui  ( in App.vue + components/NetworkSelector.vue ) 

Missing : Functionality :)

### LINKED ISSUE #246: bug: Grants and GrantRounds will not display if a wallet has not been selected

### PR DESCRIPTION
**Pull request by mds1**
Closes #242, closes #246

### CODE REVIEW

**Review by thelostone-mc — APPROVED** [review]

**Review by scco — APPROVED** [review]
looks good to me

**Comment by mk1r** [comment]
not seeing #246 resolved
Screen Shot 2021-09-21 at 12 24 15 PM
e

**Comment by mds1** [comment]
@mk1r Do you have steps to reproduce? Do I need to clear local storage, set MetaMask to a certain network, etc?

**Comment by mk1r** [comment]
@mds1 yeah mainly because I'm seeing this modal - if I'm not testing it properly, lmk

**Comment by mds1** [comment]
@mk1r Can you try the fix I just pushed? I wasn't able to get that modal to show up, but you're right it wasn't polling for users who never had a wallet connected

**Comment by mk1r** [comment]
just tried it again - hopefully I'm testing it right, from what I understand is that #246 is an issue where it shows loading screen when not connected to a wallet

that's what I'm testing for and still seeing the loading spinner & modal

**Comment by mds1** [comment]
Can you post a video showing your localstorage, metamask config, prompts, etc? If I clear local storage and disconnect my wallet, the loading screen shows but once the data it fetched it goes away and shows all grants, details, etc. And I am not sure how to trigger the modal you're seeing

**Comment by mds1** [comment]
And just to sanity check, you are using the most recent commit on this branch, c994b00afbef7dfc5233c85853ba4b43e95c8690?

**Comment by mk1r** [comment]
confirmed the branch, let me record a vid

**Comment by mk1r** [comment]
needed to change ```VITE_DGRANTS_CHAIN_ID``` to 4 - looks good, good work!

**Review by mk1r — APPROVED** [review]
needed to change ```VITE_DGRANTS_CHAIN_ID``` to 4 in my .env - looks good, nice work!

**Pull request merged**
