### PR TITLE
Add GrantRoundFactory and tests

### LINKED ISSUE #19: Implement Grants Round Factory
This issue is dependent on #17 

We will use the factory pattern to allow users to create new `GrantRound` instance. The factory should:

- [ ] Take all the parameters needed to initialize a new `GrantRound` and deploy one via a public method call
- [ ] Emit an event with the parameters when it does so
- [ ] Remove existing `GrantRounds` contract and tests

Questions:

* Should the factory method or the `GrantRound` constructor do any sanity checking of the address provided as the ERC20 token? For example, calling the `symbol` method, which would cause revert if the address passed was not an ERC20 implementation.

### PR DESCRIPTION
**Pull request by mds1**
Closes #19

In #19 we discussed adding verification to constructor args, but I pulled that out into #34 instead to avoid conflicts with #21 which is currently in progress

### CODE REVIEW

**Comment by mds1** [comment]
@wildmolasses Looks like the CI is failing even though tests pass locally, would love if you could help get that fixed!

**Comment by mds1** [comment]
CI fixed after rebasing against #36.

For reference, the problem solved by #36 was: "`yarn` normally installs deps and then runs the typechain build. but since deps didnt change, the cache step is skipping the yarn step. so the typechain stuff isn't built". Thanks @wildmolasses!

**Review by phutchins — APPROVED** [review]
Looks good to me and builds.

**Review by apbendi — APPROVED** [review]
lgtm

**Pull request merged**
