### PR TITLE
DO NOT MERGE: benchmark PR

### PR DESCRIPTION
**Pull request by thelostone-mc**
#### Description

- This page can be accessed on /benchmark
- Increase `stressCount` to increase number of pings

This does a comparison btwn alchemy + moralis

**When suite is run 1 time**  [SEE IMAGE](https://user-images.githubusercontent.com/5358146/143064708-babf4583-3fc0-42c9-83f6-c0a788f0fc9e.png)

**When suite is run 50 time** [SEE IMAGE](https://user-images.githubusercontent.com/5358146/143069291-33ae4e71-e478-4854-a583-03ca53a73ec3.png)

**When suite is run 300 times over VPN in US** [SEE IMAGE](https://user-images.githubusercontent.com/5358146/143194708-5f8757ce-0ce7-4122-9cce-e25d8ed44002.png)

**When suite is run over 500 times** [SEE IMAGE](https://user-images.githubusercontent.com/5358146/143406211-58837cf7-52b4-48b7-b25d-e50a7b58bba6.png)

Moralis seems to be better from what I can tell

Closes https://github.com/dcgtc/dgrants/issues/508
Closes https://github.com/dcgtc/dgrants/issues/487

### CODE REVIEW

**Comment by apbendi** [comment]
Screen Shot 2021-11-29 at 11 19 02 AM

**Comment by gdixon** [comment]
Here are my results from the UK:

Screenshot 2021-11-30 at 03 43 07

**Comment by mds1** [comment]
In `stressCount` I converted the `for` loop to `await Promise.all(Array.from(Array(count).keys()).map(async (i) => { try/catch func }))`, so all the RPC requests are fired off in parallel. For some reason the UI wasn't reactive (which is why I didn't push it) so I just logged them out to the console. Results of 500 runs for Alchemy and 250 for Moralis (I think Moralis blocked me from sending that many requests at once because it'd fail with CORS errors)

## Moralis

```json
{
    "slowest": {
        "fetchCodeTime": 5518,
        "fetchAllGrantAndGrantRoundsTime": "64079.20",
        "fetchContributionsTime": "20621.40",
        "fetchGrantRoundTime": "56600.30",
        "fetchLastBlockNumberTime": "2038.70"
    },
    "fastest": {
        "fetchCodeTime": "2970.30",
        "fetchAllGrantAndGrantRoundsTime": "12316.10",
        "fetchContributionsTime": "18135.30",
        "fetchGrantRoundTime": "3575.40",
        "fetchLastBlockNumberTime": "845.10"
    },
    "avg": {
        "fetchCodeTimeAvg": "4029.41",
        "fetchAllGrantAndGrantRoundsTimeAvg": "53510.27",
        "fetchContributionsTimeAvg": "20013.68",
        "fetchGrantRoundTimesAvg": "14880.15",
        "fetchLastBlockNumberTimesAvg": "1346.02"
    },
    "median": {
        "fetchCodeTimeMedian": 3995.300000000745,
        "fetchAllGrantAndGrantRoundsTimeMedian": "63716.20",
        "fetchContributionsTimeMedian": "20423.15",
        "fetchGrantRoundTimeMedian": "5425.95",
        "fetchLastBlockNumberTimeMedian": "1339.30"
    }
}
```

## Alchemy

```json
{
  "slowest": {
      "fetchCodeTime": 10589.19999999553,
      "fetchAllGrantAndGrantRoundsTime": "119997.90",
      "fetchContributionsTime": "37854.70",
      "fetchGrantRoundTime": "44177.80",
      "fetchLastBlockNumberTime": "4073.70"
  },
  "fastest": {
      "fetchCodeTime": "5889.20",
      "fetchAllGrantAndGrantRoundsTime": "81734.40",
      "fetchContributionsTime": "4204.20",
      "fetchGrantRoundTime": "12759.20",
      "fetchLastBlockNumberTime": "1038.20"
  },
  "avg": {
      "fetchCodeTimeAvg": "7731.22",
      "fetchAllGrantAndGrantRoundsTimeAvg": "103870.10",
      "fetchContributionsTimeAvg": "33165.95",
      "fetchGrantRoundTimesAvg": "26669.76",
      "fetchLastBlockNumberTimesAvg": "2460.72"
  },
  "median": {
      "fetchCodeTimeMedian": 7476.550000000745,
      "fetchAllGrantAndGrantRoundsTimeMedian": "112246.85",
      "fetchContributionsTimeMedian": "37433.55",
      "fetchGrantRoundTimeMedian": "26156.05",
      "fetchLastBlockNumberTimeMedian": "2606.95"
  }
}
```

**Comment by mds1** [comment]
Fine with me!

**Pull request closed without merging**
