### PR TITLE
grants detail ui enhancement

### PR DESCRIPTION
**Pull request by scco**
- improved the grantsdetailsrow with code from richard-ui3
- removed v-slot from that component for extra interactions
- outsourced interactions into the grantregistrygrantdetail.vue in a interaction nav bar
- removed that css from app.vue ( as it bothers me and some css )
- added a placeholder_grant.svg to use when there is no img from ipfs

### CODE REVIEW

**Comment by apbendi** [comment]
@scco I'm a little concerned with how huge the browser has to be before you get a more standard "desktop" style layout. In my normal browser layout, I'm getting a single column layout, which means I don't even see the full image above the fold:

Screen Shot 2021-09-07 at 8 06 33 AM

**Comment by mds1** [comment]
Code looks good!

Agree with @apbendi that it does seem on this branch the mobile view shows up at a wider width than expected, whereas that is not the case on `main`

Also the fact that there's no max width makes the description look a bit odd on large windows—it feels like it should be left-aligned perhaps?

image

**Comment by scco** [comment]
it's all as it should be, with intention and purpose.
i agree the demo image does not look super good in here, but its a placeholder.

**Review by apbendi — APPROVED** [review]

**Review by thelostone-mc — APPROVED** [review]

**Comment by mds1** [comment]
Started rebasing this one, but it turned out to be a pain since @scco @thelostone-mc and @mk1r all made changes to `GrantRegistryGrantDetail.vue`, so the version on `main` are causing conflicts.

There's a lot going on in that file and I'm not as familiar with it all since I haven't worked on it, so can you guys all work together on resolving this one? Happy to help as needed

**Comment by apbendi** [comment]
Closed for #185

**Pull request closed without merging**
