### PR TITLE
design-fixes-5

### PR DESCRIPTION
**Pull request by scco**
- Filter Nav : adding hover effect on nav elements
- Grant & Round Cards adding hover effect
- Cart : fixing structure to prevent double displayed "estimated matching" on multiple rounds
- Global Css : .link gets a hover effect and no underline but border-bottom line (looks nicer)
- about modal : apply .link to licens and help link
- Grant Card - apply .link to address
- Main Nav Menu ( When hover on logo ) : fixed broken css styles and semantic of the menu
- grantregistrygrantdetail & grantround : removed css from !loading
- design 404 page

### CODE REVIEW

**Comment by scco** [comment]
the test  seems to fail because something non-css/html related .
"lerna ERR! yarn run test exited 5 in '@dgrants/contracts'"

**Comment by mds1** [comment]
I'll look into the CI failures

LGTM, just one comment—for the Grant Cards and Round Cards, right now you have to click the image to view the detail page. I feel like you should also be able to click the grant name, but currently you can't

**Comment by mds1** [comment]
Somehow on `main`:
- CI times out
- Contract tests fail when run locally

But on the `polygon-support` branch for #281, CI passes and tests pass locally. So let's not worry about the CI here, and we'll just make sure everything looks good on main after #281 and this are both merged

**Comment by scco** [comment]
"for the Grant Cards and Round Cards, right now you have to click the image to view the detail page. I feel like you should also be able to click the grant name"

yes i agree, but i do not visually wana have the round/grant name underlined . and same time i want to keep consistency with all content links have underline + hover grey-400 .  so i right now did a little update - linking the full component to detail pages,  what is exactly how i planed it .

**Review by mds1 — APPROVED** [review]

**Review by thelostone-mc — APPROVED** [review]

**Pull request merged**
