### PR TITLE
Jw fix docs

### PR DESCRIPTION
**Pull request by jjwoz**

### CODE REVIEW

**Comment by mk1r** [comment]
ready for review?

**Review by phutchins — APPROVED** [review]

**Review by mk1r — APPROVED** [review]
nice work!

**Comment by mk1r** [comment]
if you need assistance, rebasing lmk - seems it might be a little longer for this one

**Comment by jjwoz** [comment]
Sounds good to me @mk1r

**Comment by mk1r** [comment]
still seeing conflicts, but we can take a look after the standup

**Comment by mk1r** [comment]
closing in favor of #475

**Pull request closed without merging**
